name: sep

dependencies:
  - numpy=1.9
  - python=3.7
  - matplotlib=2.2.* 
  - pandas=0.25.*
  - librosa=0.6.*
  - jupyter=1.0
  - tensorflow=1.13.*
  - keras=2.2.*
  - scikit-learn=0.20.*
  - h5py=2.10
  - jsonpickle=1.2
  
  
  
